project:
  type: website
  output-dir: docs

website:
  favicon: figs/scout_yarn_logo_clear_bg.png
  title: "Scout Knits Stuff!"
  navbar:
    logo: figs/scout_yarn_logo_clear_bg.png
    title: false
    right:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Blog
      - href: knitting_places.qmd
        text: Knitting Places
      - icon: github
        href: https://github.com/scoutcleonard/knitting_quarto_website
        aria-label: GitHub
  repo-url: https://github.com/scoutcleonard/knitting_quarto_website

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true

editor: visual